### ISSUE TITLE
YAMNET Training for Bird Dataset

### ISSUE THREAD

**Issue by Maanikya** [vsnupoudel/Audio-Classification--transfer-learning-and-fine-tuning--Android-application#1]
Dear Sir,

First of all, thank you very much for your email and replying at the earliest.

My problems are as follows:
1. I'm a beginner to ML and DL field.
2. I'm facing problem on replacing the dataset you used into the dataset that I want to use without using CSV file as Metadata.
3. I'm finding it hard to wrap my head around the functions that you used to creating "train_ds" variable to feed to the model for training

My goal:
To develop a YAMNET model for bird audio classification and to implement it as an Android App.

I'm doing this as a team for our major project.

Link for the Dataset: https://www.kaggle.com/datasets/maanikya/yamnet-dataset-v2

Sir, can you please help us in tweaking the code to fit our requirements?

**Comment by vsnupoudel** [comment]
Not able to look into all details now, but following are some recommendations.
1. tensorflow io  seems to not work on resampling.. Please use scipy...  Notebook example below
https://www.tensorflow.org/hub/tutorials/yamnet
2. Original notebook ( where tfio is used)
https://www.tensorflow.org/tutorials/audio/transfer_learning_audio
3. Follow the dataset conventions in the notebook. Use the same conventions in your csv file ( which has path to audio files)
4.  For training the data, I believe first the embeddings are being extracted. And these are used as features to finetune the classification.  
I can revisit the notebook later, and update on 4.
Hope it was useful..
Also, please paste and specific errors you get while running the notebooks..

**Comment by Maanikya** [comment]
Sure sir, I will try to incorporate your suggestions.

I was able to train a simple YAMNET model using the dataset that I wanted
to.

I will try and improve it.

Thank you.

**Comment by Maanikya** [comment]
I will also share the notebook with you tomorrow.

**Comment by vsnupoudel** [comment]
Also, tfio apparently works with a specific tf version. 
![IMG_20230419_013349](https://user-images.githubusercontent.com/19270934/232892507-4d79eb0c-47db-47db-b1d2-0670f4865e88.jpg)

**Comment by Maanikya** [comment]
Dear Sir,

I have attached the Notebook in this email. I have used a rather simple
approach and I'm satisfied with the results that it provides for the
time being. Part of the reason being time constraint due to deadlines and
other reasons.

However I will try to implement your suggestions in the work such as
waveform resampling if it is not in the desired sample rate, etc.

Thank you for your quick replies and helping me out, especially by
sacrificing your sleep.

So I'm concerned about your health and your dedication to my help as you
have been helping me without even asking anything. It is a rare sight to
see someone help a stranger and be this kind. So sir, for the time being,
as I have got some satisfactory results, I think I can manage on my own
from here on. Hence please focus on your work and if I need any assistance,
I'll let you know by dropping an email.

Once again, Thank you so much for your help and support. 👏
